[package]
name         = "signal-spirit"
version      = "0.16.0"
edition      = "2024"
rust-version = "1.89"
license      = "MIT OR Apache-2.0"
repository   = "https://github.com/LiGoldragon/signal-spirit"
description  = "Signal contract for the ordinary spirit surface."
publish      = false
links        = "signal-spirit"
build        = "build.rs"

[lib]
name = "signal_spirit"
path = "src/lib.rs"

[features]
default = ["dotos-text"]
dotos-text = ["dep:dotos", "signal-frame/dotos-text"]

[dependencies]
signal-domain = { git = "https://github.com/LiGoldragon/signal-domain.git", rev = "cc97101ebaff3173b55dd014bf1dda511534e011", default-features = false }
signal-frame = { git = "https://github.com/LiGoldragon/signal-frame.git", rev = "01676293a623d97b65e320d4138c4b480c6d5dad", default-features = false }
dotos = { git = "https://github.com/LiGoldragon/dotos.git", rev = "80c7b17f7ad3cf547d2624c6a243e5de5f85c9f3", optional = true }
protos = { git = "https://github.com/LiGoldragon/protos.git", rev = "d06c4a9" }
rkyv = { version = "=0.8.17", default-features = false, features = ["std", "bytecheck", "little_endian", "pointer_width_32", "unaligned"] }

[build-dependencies]
name-table = { git = "https://github.com/LiGoldragon/name-table.git", rev = "7dd5db15c16b4246c83d049c759415d3252a7d43" }
rust-logos = { git = "https://github.com/LiGoldragon/rust-logos.git", rev = "728647e" }
schema-rust = { git = "https://github.com/LiGoldragon/schema-rust.git", rev = "d28ead7" }
sema-translator = { git = "https://github.com/LiGoldragon/sema-translator.git", rev = "118d7a3", default-features = false, features = ["bootstrap"] }
core-nomos = { git = "https://github.com/LiGoldragon/core-nomos.git", rev = "419dcba" }

[dev-dependencies]

[lints.rust]
unsafe_code = "forbid"
unused      = { level = "warn", priority = -1 }
dead_code   = "warn"
