// @generated by schema-rust from an authority-verified bootstrap source
// source-digest: blake3:c877ff9e5f4d20324f223b4141f20f3bdd16d12c5131940ab0a7031ddc8c7e52

pub struct Count(Query);

pub struct LookupStash(StashHandle);

pub struct Record(RecordRequest);

pub struct Lookup(RecordIdentifier);

pub struct Marker(Unit);

pub struct Observe(Query);

pub struct Version(Unit);

pub struct Versioned(VersionReport);

pub struct Counted(RecordCount);

pub struct LookedUp(FoundRecord);

pub struct Stashed(StashedObservation);

pub struct Marked(DatabaseMarker);

pub struct Observed(RecordSet);

pub struct Recorded(RecordIdentifier);

// Generation gap: rust-logos does not yet emit derives; these are
// manually added for the Refusal trait's Error bound (Debug + Display).
#[derive(Debug)]
pub struct QueryRejected(QueryRefusal, Explanation);

#[derive(Debug)]
pub struct AdmissionRejected(GuardianReason, Explanation);

pub struct Observer(IntentEvent);

pub enum IntentEvent {
    IntentRecorded,
}

pub struct VerbatimQuote(QuoteText);

pub enum ImportanceSelection {
    ExactImportance(Importance),
    Any,
    AtMostImportance(Importance),
    AtLeastImportance(Importance),
}

pub struct RecordCount(Integer);

pub struct Domains(Vec<signal_domain::Domain>);

pub struct Testimony(Vec<VerbatimQuote>);

pub struct QuoteText(String);

pub struct IntentRecorded(Entry, RecordIdentifier);

pub struct VersionText(String);

pub struct VersionReport(VersionText);

pub enum KeywordMatch {
    AllKeywords(Keywords),
    Any,
    AnyKeyword(Keywords),
}

pub struct StashHandle(Integer);

#[derive(Debug)]
pub enum QueryRefusal {
    InvalidDomainSelection,
}

pub enum DomainMatch {
    Full(signal_domain::DomainScopes),
    Any,
    Partial(signal_domain::DomainScopes),
}

#[derive(Debug)]
pub struct Explanation(String);

pub struct StashedObservation(StashHandle, RecordSet);

pub struct CommitSequence(Integer);

pub enum TextMatch {
    ContainsText(SearchText),
    Any,
}

pub struct RecordIdentifier(String);

pub struct Keyword(String);

pub struct StateDigest(Integer);

#[derive(Debug)]
pub enum GuardianReason {
    Duplicate,
    ImportanceUnsupported,
    Matter,
    Contradiction,
    InsufficientWarrant,
}

pub enum Kind {
    Decision,
    Principle,
    Correction,
    Constraint,
    Clarification,
}

pub struct Entry(Domains, Kind, Description, Importance);

pub struct RecordRequest(Entry, Justification);

pub struct Query(DomainMatch, KeywordMatch, TextMatch, SelectedKind, ImportanceSelection);

pub struct RecordSet(Vec<ObservedRecord>);

pub struct ObservedRecord(RecordIdentifier, Entry);

pub struct Importance(Magnitude);

pub struct DatabaseMarker(CommitSequence, StateDigest);

pub struct Keywords(Vec<Keyword>);

pub struct Justification(Testimony, Reasoning);

pub struct SearchText(String);

pub struct Description(String);

pub struct Reasoning(String);

pub struct FoundRecord(RecordIdentifier, Entry);

pub struct SelectedKind(Option<Kind>);

pub enum Magnitude {
    Minimum,
    Maximum,
    VeryHigh,
    Zero,
    VeryLow,
    Low,
    High,
    Medium,
}

impl protos::Refusal for QueryRejected {

}

impl protos::Refusal for AdmissionRejected {

}

impl protos::Input for Count {

}

impl protos::Input for LookupStash {

}

impl protos::Input for Record {

}

impl protos::Input for Lookup {

}

impl protos::Input for Marker {

}

impl protos::Input for Observe {

}

impl protos::Input for Version {

}

impl protos::Output for Versioned {

}

impl protos::Output for Counted {

}

impl protos::Output for LookedUp {

}

impl protos::Output for Stashed {

}

impl protos::Output for Marked {

}

impl protos::Output for Observed {

}

impl protos::Output for Recorded {

}

impl protos::Stream for Observer {

}