//! Schema-derived ordinary Signal contract for the `spirit` surface.
//!
//! `schema/domain.schema` and `schema/signal.schema` are the source of truth.
//! The checked-in files under `src/schema/` are generated by `schema-rust-next`
//! as a wire contract. Runtime actors, sockets, storage, guardian calls, and
//! daemon lowering live in `spirit`.

#[rustfmt::skip]
pub mod schema;

pub use schema::signal::*;

pub type SpiritRequest = Input;
pub type SpiritReply = Output;
pub type SpiritFrame = signal_frame::StreamingFrame<Input, Output, IntentEvent>;
pub type SpiritFrameBody = signal_frame::StreamingFrameBody<Input, Output, IntentEvent>;

impl ConfigurationPath {
    pub fn as_str(&self) -> &str {
        self.payload().as_str()
    }
}

impl SpiritGuardianProviderName {
    pub fn as_str(&self) -> &str {
        self.payload().as_str()
    }
}

impl SpiritGuardianModelName {
    pub fn as_str(&self) -> &str {
        self.payload().as_str()
    }
}

impl SpiritGuardianTimeoutMilliseconds {
    pub fn into_u64(self) -> u64 {
        self.into_payload()
    }
}

impl SpiritGuardianMaximumOutputTokens {
    pub fn into_u64(self) -> u64 {
        self.into_payload()
    }
}

impl SpiritGuardianAgentConfiguration {
    pub fn new(
        agent_socket_path: ConfigurationPath,
        provider_name: Option<SpiritGuardianProviderName>,
        model_name: Option<SpiritGuardianModelName>,
        timeout_milliseconds: SpiritGuardianTimeoutMilliseconds,
        maximum_output_tokens: Option<SpiritGuardianMaximumOutputTokens>,
    ) -> Self {
        Self {
            agent_socket_path,
            provider_name,
            model_name,
            timeout_milliseconds,
            maximum_output_tokens,
        }
    }

    pub fn agent_socket_path(&self) -> &str {
        self.agent_socket_path.payload().as_str()
    }

    pub fn provider_name(&self) -> Option<&str> {
        self.provider_name
            .as_ref()
            .map(SpiritGuardianProviderName::as_str)
    }

    pub fn model_name(&self) -> Option<&str> {
        self.model_name.as_ref().map(SpiritGuardianModelName::as_str)
    }

    pub fn timeout_milliseconds(&self) -> u64 {
        self.timeout_milliseconds.clone().into_u64()
    }

    pub fn maximum_output_tokens(&self) -> Option<u64> {
        self.maximum_output_tokens
            .clone()
            .map(SpiritGuardianMaximumOutputTokens::into_u64)
    }
}

impl SpiritDaemonConfiguration {
    pub fn new(socket_path: ConfigurationPath, database_path: ConfigurationPath) -> Self {
        Self {
            socket_path,
            meta_socket_path: None,
            database_path,
            trace_socket_path: None,
            guardian_agent_configuration: None,
        }
    }

    pub fn with_meta_socket_path(mut self, meta_socket_path: ConfigurationPath) -> Self {
        self.meta_socket_path = Some(meta_socket_path);
        self
    }

    pub fn with_guardian_agent_configuration(
        mut self,
        guardian_agent_configuration: SpiritGuardianAgentConfiguration,
    ) -> Self {
        self.guardian_agent_configuration = Some(guardian_agent_configuration);
        self
    }

    pub fn with_trace_socket_path(mut self, trace_socket_path: ConfigurationPath) -> Self {
        self.trace_socket_path = Some(trace_socket_path);
        self
    }

    pub fn socket_path(&self) -> &str {
        self.socket_path.as_str()
    }

    pub fn meta_socket_path(&self) -> Option<&str> {
        self.meta_socket_path.as_ref().map(ConfigurationPath::as_str)
    }

    pub fn database_path(&self) -> &str {
        self.database_path.as_str()
    }

    pub fn trace_socket_path(&self) -> Option<&str> {
        self.trace_socket_path.as_ref().map(ConfigurationPath::as_str)
    }

    pub fn guardian_agent_configuration(&self) -> Option<&SpiritGuardianAgentConfiguration> {
        self.guardian_agent_configuration.as_ref()
    }

    pub fn from_rkyv_bytes(bytes: &[u8]) -> Result<Self, SpiritDaemonConfigurationArchiveError> {
        rkyv::from_bytes::<Self, rkyv::rancor::Error>(bytes)
            .map_err(|_| SpiritDaemonConfigurationArchiveError::Decode)
    }

    pub fn to_rkyv_bytes(&self) -> Result<Vec<u8>, SpiritDaemonConfigurationArchiveError> {
        rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map(|bytes| bytes.to_vec())
            .map_err(|_| SpiritDaemonConfigurationArchiveError::Encode)
    }
}

#[derive(Debug, thiserror::Error)]
pub enum SpiritDaemonConfigurationArchiveError {
    #[error("failed to encode spirit daemon configuration archive")]
    Encode,

    #[error("failed to decode spirit daemon configuration archive")]
    Decode,
}
